name: Core Dump Analysis

on:
  issues:
    types: [opened]

jobs:
  analyze-core-dump:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Core Dump Report') || contains(github.event.issue.body, 'Core Dump Report')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run riberry-analyze-core-dump
        id: analyze
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          ANALYSIS_RESULT=$(riberry-analyze-core-dump --text "$ISSUE_BODY")
          echo "analysis<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ANALYSIS_RESULT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Comment analysis result
        uses: actions/github-script@v7
        with:
          script: |
            const output = `${{ steps.analyze.outputs.analysis }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Core Dump Analysis Result\n\n\`\`\`\n${output}\n\`\`\``
            });
